export const slides = [
  {
    id: 1,
    color: "red",
    title: "UNDO Carbon",
    main: `Actively developing B2B and internal tools to facilitate efficient carbon capture from the environment. Focused on creating solutions that empower users to enhance their carbon sequestration efforts.`,
    link: "https://ram-ui.vercel.app/",
    src: "storybook.png",
  },
  {
    id: 2,
    color: "red",
    title: "React Component Library",
    main: `A personal React based UI component library. Each component has been crafted with a focus on responsiveness, accessibility, and user experience.`,
    link: "https://ram-ui.vercel.app/",
    src: "storybook.png",
  },
  {
    id: 3,
    color: "red",
    title: "Quick Polls",
    main: `A real-time polling app, with functionality to restrict polls to select audiences. Built with React and PostgreSQL, this app demonstrates efficient backend integration, and modern web practices.`,
    link: "https://quickpolls.vercel.app/",
    src: "quickPolls.png",
  },
  {
    id: 4,
    color: "red",
    title: "Storefronts",
    main: `A landing page for an upcoming ecommerce provider in Egypt, built with React, with a focus on clean, accessible, and approachable design. Support for both English and Arabic is included to cater for a diverse audience.`,
    link: "https://www.storefronts.digital/",
    src: "adeptMedia.png",
  },
  {
    id: 5,
    color: "red",
    title: "Adept Media",
    main: `A static website built with NextJS, ensuring a responsive and modern user interface. This platform merges the nuances of language services with digital engagement, representing an understanding of business needs in the contemporary digital landscape.`,
    link: "https://adeptmedia.vercel.app/",
    src: "adeptMedia.png",
  },
];
